
name: Publish package to NPM Package Registry

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
          scope: "@neobeach"

      - name: Check if @neobeach/core version has been updated
        id: core
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: package.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish @neobeach/core
        if: steps.core.outputs.changed == 'true'
        run: npm publish core --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
